--(1).1
CREATE TABLE STUDENT_LIST(
    HAK_BUN VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    GRADE INT,
    MAJOR VARCHAR2(20)
);
--(1).2
CREATE TABLE PROFESSOR_LIST(
    NUM VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    TEL VARCHAR2(20) NOT NULL,
    MAJOR VARCHAR2(20) NOT NULL,
    AGE INT
);
--(1).3
INSERT INTO STUDENT_LIST VALUES ('123','김길동',1,'컴퓨터공학');
INSERT INTO STUDENT_LIST VALUES ('124','권길동',2,'통계');
INSERT INTO STUDENT_LIST VALUES ('125','박길동',4,'국어국문');
INSERT INTO STUDENT_LIST VALUES ('126','정길동',1,'무역');
INSERT INTO STUDENT_LIST VALUES ('127','이길동',3,'국어국문');
--(1).4
INSERT INTO PROFESSOR_LIST VALUES ('1','김철수','010-0000-0000','국어국문',25);
INSERT INTO PROFESSOR_LIST VALUES ('2','이영희','010-1111-1111','통계',45);
INSERT INTO PROFESSOR_LIST VALUES ('3','박훈','010-2222-2222','컴퓨터공학',35);
--(1).5
SELECT * FROM STUDENT_LIST;
SELECT * FROM PROFESSOR_LIST;
--(1).6
SELECT NAME, MAJOR FROM STUDENT_LIST;
--(1).7
SELECT HAK_BUN, NAME, GRADE FROM STUDENT_LIST WHERE GRADE >= 3;
--(1).8
SELECT NAME, TEL, MAJOR FROM PROFESSOR_LIST WHERE NUM = 1;
--(1).9
SELECT NAME, AGE FROM PROFESSOR_LIST WHERE AGE >= 35;
--(1).10
DROP TABLE STUDENT_LIST;
DROP TABLE PROFESSOR_LIST;
-------------------------------------------------------------------------------------------------
--(2).1
CREATE TABLE EMPLOYEE_LIST(
    E_NUM VARCHAR2(10) PRIMARY KEY,
    E_NAME VARCHAR2(20) NOT NULL,
    DEPARTMENT VARCHAR2(20) NOT NULL,
    AGE INT
);
--(2).2
CREATE TABLE DEPARTMENT_LIST(
    D_NUM VARCHAR2(10) PRIMARY KEY,
    D_NAME VARCHAR(20) NOT NULL,
    E_COUNT INT
);
--(2).3
INSERT INTO EMPLOYEE_LIST VALUES ('521', '김길동', '경영행정부', 25);
INSERT INTO EMPLOYEE_LIST VALUES ('525', '이길동', '교무부', 40);
INSERT INTO EMPLOYEE_LIST VALUES ('523', '최길동', '교무부', 30);
INSERT INTO EMPLOYEE_LIST VALUES ('524', '정길동', '교무지원부', 29);
--(2).4
INSERT INTO DEPARTMENT_LIST VALUES ('1', '교무부', 30);
INSERT INTO DEPARTMENT_LIST VALUES ('2', '교무지원부', 15);
INSERT INTO DEPARTMENT_LIST VALUES ('3', '경영행정부', 10);
--(2).5
SELECT * FROM EMPLOYEE_LIST;
SELECT * FROM DEPARTMENT_LIST;
--(2).6
SELECT E_NAME, DEPARTMENT FROM EMPLOYEE_LIST;
--(2).7
SELECT E_NUM, E_NAME, DEPARTMENT FROM EMPLOYEE_LIST WHERE DEPARTMENT = '교무부';
--(2).8
SELECT D_NAME, E_COUNT FROM DEPARTMENT_LIST WHERE E_COUNT > 10;
--(2).9
SELECT * FROM DEPARTMENT_LIST WHERE D_NUM = 2;
--(2).10
DROP TABLE EMPLOYEE_LIST;
DROP TABLE DEPARTMENT_LIST;

COMMIT;
