-- DJStudent 테이블 만들기 : 학번, 이름, 학과명을 저장함 (모두 varchar2로 할 것)
CREATE TABLE DJStudent(
    STUDENT_ID VARCHAR2(20),
    NAME VARCHAR2(20),
    MAJOR VARCHAR2(20)
);
-- KBMajor 테이블 만들기 : 학과코드(char(3)) 학과명(varchar2)
CREATE TABLE KBMajor(
    MAJOR_CODE CHAR(3) PRIMARY KEY,
    MAJOR VARCHAR2(20)
);
-- KBStudent 테이블 만들기 : 학번 이름 학과코드(char(3))
CREATE TABLE KBSTUDENT(
    STUDENT_ID VARCHAR2(20)PRIMARY KEY,
    NAME VARCHAR2(20),
    MAJOR_CODE CHAR(3)
);
-- 각 테이블에 예시 데이터 5개 이상 추가하기
INSERT INTO DJStudent VALUES ('101', '김민수', '경영');
INSERT INTO DJStudent VALUES ('102', '이철수', '통계');
INSERT INTO DJStudent VALUES ('103', '정민주', '컴공');
INSERT INTO DJStudent VALUES ('104', '이진수', '기계');
INSERT INTO DJStudent VALUES ('105', '황훈', '수학');

INSERT INTO KBMajor VALUES ('1','경영');
INSERT INTO KBMajor VALUES ('2','통계');
INSERT INTO KBMajor VALUES ('3','컴공');
INSERT INTO KBMajor VALUES ('4','기계');
INSERT INTO KBMajor VALUES ('5','수학');

INSERT INTO KBSTUDENT VALUES ('111', '김일중', '1');
INSERT INTO KBSTUDENT VALUES ('112', '김이중', '2');
INSERT INTO KBSTUDENT VALUES ('113', '김삼중', '3');
INSERT INTO KBSTUDENT VALUES ('114', '김사중', '4');
INSERT INTO KBSTUDENT VALUES ('115', '김오중', '5');

UPDATE KBSTUDENT SET NAME = '이유나' WHERE STUDENT_ID = '113';

SELECT * FROM DJStudent;
SELECT * FROM KBMajor;
SELECT * FROM KBStudent;    -- 외래키를 추가함, 참고할 테이블은 KBMAJOR의 MAJOR_CODE

-- 전공테이블의 MAJOR_CODE를 '참조' 하여서 학생 테이블의 데이터를 관리하겠다는 의미
-- 전공테이블에 없는 전공은 추가할 수가 없다.
ALTER TABLE KBSTUDENT ADD CONSTRAINT FK_CODE FOREIGN KEY (MAJOR_CODE) REFERENCES KBMAJOR(MAJOR_CODE);

INSERT INTO KBSTUDENT VALUES('116', '정용억', '1'); -- OK
INSERT INTO KBSTUDENT VALUES('117', '홍주환', '111'); -- 학과코드가 111인 과는 현재 없는 상태

INSERT INTO KBMAJOR VALUES ('6', '화공');
INSERT INTO KBSTUDENT VALUES('117', '권병진', '6');

-- JOIN 두 개 이상의 테이블을 공통된 열(COLUMN)로 묶는다.
SELECT STUDENT_ID, KBSTUDENT.NAME, KBMAJOR.MAJOR FROM KBSTUDENT JOIN KBMAJOR ON KBSTUDENT.MAJOR_CODE = KBMAJOR.MAJOR_CODE;
-- 위에거랑 밑에거 같은거임
SELECT STUDENT_ID 학번, KBSTUDENT.NAME 학생이름, KBMAJOR.MAJOR 학과명 FROM KBSTUDENT JOIN KBMAJOR ON KBSTUDENT.MAJOR_CODE = KBMAJOR.MAJOR_CODE;
-- WHERE을 이용한 JOIN문, 두 테이브을 콤마(,)로 묶고, WHERE문을 사용함
SELECT STUDENT_ID 학번, KBSTUDENT.NAME 학생이름, KBMAJOR.MAJOR 학과명 FROM KBSTUDENT, KBMAJOR WHERE KBSTUDENT.MAJOR_CODE = KBMAJOR.MAJOR_CODE;


